<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CatalogAndPaymentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('categories')->insert([
            [
                'id' => 1,
                'client_id' => 1,
                'name' => 'Stroller',
                'slug' => 'stroller',
                'description' => 'Kereta dorong bayi berbagai merk.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'client_id' => 1,
                'name' => 'Car Seat',
                'slug' => 'car-seat',
                'description' => 'Kursi keselamatan bayi untuk di mobil.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'client_id' => 1,
                'name' => 'Box Bayi & Tempat Tidur',
                'slug' => 'box-bayi',
                'description' => 'Tempat tidur dan box bayi.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'client_id' => 1,
                'name' => 'Sterilizer & Pompa ASI',
                'slug' => 'sterilizer-pompa-asi',
                'description' => 'Alat pembersih dan perlengkapan menyusui.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

        DB::table('products')->insert([
            [
                'id' => 1,
                'client_id' => 1,
                'category_id' => 1,
                'name' => 'Stroller Babyzen YOYO2 Black Frame',
                'slug' => 'stroller-babyzen-yoyo2',
                'description' => 'Kereta dorong ringkas untuk travel.',
                'rental_price_per_day' => 150000.00,
                'deposit_fee' => 300000.00,
                'main_image' => 'products/babyzen-yoyo2.jpg',
                'status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'client_id' => 1,
                'category_id' => 2,
                'name' => 'Car Seat Joie Spin 360 ISOFIX',
                'slug' => 'car-seat-joie-spin-360',
                'description' => 'Car seat bisa berputar 360 derajat.',
                'rental_price_per_day' => 125000.00,
                'deposit_fee' => 250000.00,
                'main_image' => 'products/joie-spin360.jpg',
                'status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'client_id' => 1,
                'category_id' => 3,
                'name' => 'Box Bayi Nuna Sena AIRE Timber',
                'slug' => 'box-bayi-nuna-sena-aire',
                'description' => 'Box bayi portabel sangat nyaman.',
                'rental_price_per_day' => 100000.00,
                'deposit_fee' => 200000.00,
                'main_image' => 'products/nuna-sena.jpg',
                'status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'client_id' => 1,
                'category_id' => 4,
                'name' => 'Haenim UV Sterilizer 4G Plus',
                'slug' => 'haenim-uv-sterilizer-4g',
                'description' => 'Mesin sterilisasi botol dan perlengkapan.',
                'rental_price_per_day' => 80000.00,
                'deposit_fee' => 150000.00,
                'main_image' => 'products/haenim-4g.jpg',
                'status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 5,
                'client_id' => 1,
                'category_id' => 1,
                'name' => 'Cocolatte Pockit Gen 7',
                'slug' => 'cocolatte-pockit-gen7',
                'description' => 'Stroller pockit ultra kompak.',
                'rental_price_per_day' => 90000.00,
                'deposit_fee' => 150000.00,
                'main_image' => 'products/cocolatte-pockit.jpg',
                'status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 6,
                'client_id' => 1,
                'category_id' => 4,
                'name' => 'Spectra S1 Plus Breast Pump',
                'slug' => 'spectra-s1-plus',
                'description' => 'Pompa ASI elektrik hospital grade.',
                'rental_price_per_day' => 110000.00,
                'deposit_fee' => 200000.00,
                'main_image' => 'products/spectra-s1.jpg',
                'status' => 'aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

        DB::table('equipment_units')->insert([
            [
                'id' => 1,
                'client_id' => 1,
                'product_id' => 1,
                'unit_code' => 'BBR-YOYO-01',
                'serial_number' => 'SN-BBY-001',
                'condition' => 'baik',
                'status' => 'tersedia',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'client_id' => 1,
                'product_id' => 1,
                'unit_code' => 'BBR-YOYO-02',
                'serial_number' => 'SN-BBY-002',
                'condition' => 'baik',
                'status' => 'disewa',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'client_id' => 1,
                'product_id' => 2,
                'unit_code' => 'BBR-JOIE-01',
                'serial_number' => 'SN-JOIE-001',
                'condition' => 'baik',
                'status' => 'tersedia',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'client_id' => 1,
                'product_id' => 3,
                'unit_code' => 'BBR-NUNA-01',
                'serial_number' => 'SN-NUN-001',
                'condition' => 'baik',
                'status' => 'tersedia',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 5,
                'client_id' => 1,
                'product_id' => 4,
                'unit_code' => 'BBR-HNM-01',
                'serial_number' => 'SN-HNM-001',
                'condition' => 'baik',
                'status' => 'tersedia',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 6,
                'client_id' => 1,
                'product_id' => 5,
                'unit_code' => 'BBR-CCLT-01',
                'serial_number' => 'SN-CCL-001',
                'condition' => 'baik',
                'status' => 'tersedia',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 7,
                'client_id' => 1,
                'product_id' => 6,
                'unit_code' => 'BBR-SPC-01',
                'serial_number' => 'SN-SPC-001',
                'condition' => 'baik',
                'status' => 'tersedia',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 8,
                'client_id' => 1,
                'product_id' => 6,
                'unit_code' => 'BBR-SPC-02',
                'serial_number' => 'SN-SPC-002',
                'condition' => 'baik',
                'status' => 'tersedia',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

        DB::table('client_payment_methods')->insert([
            [
                'id' => 1,
                'client_id' => 1,
                'bank_name' => 'BCA',
                'account_number' => '8830991122',
                'account_holder' => 'Baby Rental Studio Malang',
                'qris_image' => 'payments/qris-bca.png',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'client_id' => 1,
                'bank_name' => 'Mandiri',
                'account_number' => '1440008877665',
                'account_holder' => 'Baby Rental Studio Malang',
                'qris_image' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

        DB::table('notifications')->insert([
            'id' => 1,
            'client_id' => 1,
            'user_id' => 2,
            'title' => 'Pesanan Baru #ORD-20261001-001',
            'message' => 'Rizky Pelanggan telah membuat pesanan sewa baru.',
            'type' => 'pesanan',
            'is_read' => false,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);
    }
}
